local arial = require 'requires.arial'
local neorg = require 'requires.neorg'
local neoscroll = require 'requires.neoscroll'
local telescope = require 'requires.telescope'
local todo_comments = require 'requires.todo-comments'
local nvim_notify = require 'requires.nvim-notify'
